name = "Gravitas2"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae31db3f11c34812f46d06db5ee5485b08d701ce479a467008df559861d58bbd"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
