name = "Gravitas2"
version = "0.4.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ca7fee4cbef5c9a4403ae4f8c167460dc73151335055520828052dffa90f1f24"

[versions]
forge = "47.3.0"
minecraft = "1.20.1"
